LearningEnglishApp/LearningEnglishApp/Areas/Admin/Controllers/WordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LearningEnglishApp.Data;
using LearningEnglishApp.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LearningEnglishApp.Controllers
{
    [Area("Admin")]
    public class WordsController : Controller
    {

        private readonly ApplicationDbContext _db;
        [BindProperty]
        public WordsViewModel WordsVM { get; set; }
        public WordsController(ApplicationDbContext db)
        {
            _db = db;
            WordsVM = new WordsViewModel()
            {
                LevelCategories = _db.LevelCategory.ToList(),
                AreaCategories = _db.AreaCategory.ToList(),
                Word = new Models.Word()
            };
        }
        public async Task<IActionResult> Index()
        {
            var words = _db.Word.Include(m => m.LevelCategory).Include(m => m.AreaCategory);
            return View(await words.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(WordsVM);
        }
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            
            var theSameAreaName = await _db.Word.Where(m => m.InPolish == WordsVM.Word.InPolish 
                                                        || m.InEnglish == WordsVM.Word.InEnglish).FirstOrDefaultAsync();
            if (theSameAreaName == null)
            {
                _db.Word.Add(WordsVM.Word);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                WordsVM.LevelCategories = _db.LevelCategory.ToList();
                WordsVM.AreaCategories = _db.AreaCategory.ToList();
                TempData["Message"] = "The word already exist!";
                return View(WordsVM);
            }
            

        }

        public async Task<IActionResult> Edit (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            WordsVM.Word = await _db.Word.Include(m => m.AreaCategory).Include(m => m.LevelCategory).SingleOrDefaultAsync(m => m.Id == id);

            if (WordsVM.Word == null)
            {
                return NotFound();
            }

            return View(WordsVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                var wordFromDb = await _db.Word.Where(m => m.Id == WordsVM.Word.Id).FirstOrDefaultAsync();
                wordFromDb.InPolish = WordsVM.Word.InPolish;
                wordFromDb.InEnglish = WordsVM.Word.InEnglish;
                wordFromDb.LevelCategoryId = WordsVM.Word.LevelCategoryId;
                wordFromDb.AreaCategoryId = WordsVM.Word.AreaCategoryId;
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(WordsVM);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            WordsVM.Word = await _db.Word.Include(m => m.AreaCategory).Include(m => m.LevelCategory).SingleOrDefaultAsync(m => m.Id == id);

            if (WordsVM.Word == null)
            {
                return NotFound();
            }

            return View(WordsVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            WordsVM.Word = await _db.Word.Include(m => m.AreaCategory).Include(m => m.LevelCategory).SingleOrDefaultAsync(m => m.Id == id);

            if (WordsVM.Word == null)
            {
                return NotFound();
            }

            return View(WordsVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteDone(int id)
        {
            var word = await _db.Word.FirstAsync(m => m.Id == id);
            _db.Word.Remove(word);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

LearningEnglishApp/LearningEnglishApp/Areas/Teacher/Controllers/PulaController.cs
using LearningEnglishApp.Data;
using LearningEnglishApp.Models;
using LearningEnglishApp.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LearningEnglishApp.Areas.Teacher.Controllers
{
    [Area("Teacher")]
    public class PulaController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PulaController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var pule = _db.Pula.ToList();
            return View(pule);
        }
        [HttpGet]
        public IActionResult ListAllWords(int pulaId)
        {
            var words = _db.WyrazyPula.Where(p => p.PulaId == pulaId).Include(m => m.Wyraz).ToList();
            return View(words);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Pula pula)
        {
            if (ModelState.IsValid)
            {
                pula.Data = DateTime.Now;
                var theSamePulaName = _db.Pula.Where(p => p.Nazwa == pula.Nazwa).Any();
                if (theSamePulaName == false)
                {
                    _db.Add(pula);
                    _db.SaveChanges();
                }
            }
            return RedirectToAction("AddGroups", pula);
        }
        [HttpGet]
        public IActionResult AddGroups(Pula pula)
        {
            var groupsVM = new GroupsViewModel();
            GrupyDoPuli grupyDoPuli = new GrupyDoPuli();
            grupyDoPuli.PulaId = pula.Id;
            groupsVM.GrupyDoPuli = grupyDoPuli;
            groupsVM.Grupy = _db.Grupa.ToList();
            return View(groupsVM);
        }
        [HttpPost]
        public IActionResult AddGroups(GroupsViewModel VM)
        {
            var grupy = _db.Grupa.ToList();
            var selectedItems = new List<string>();
            int pulaId = VM.GrupyDoPuli.PulaId;
            foreach (var item in grupy)
            {
                string selected = Request.Form[item.Nazwa].ToString();
                if (!string.IsNullOrEmpty(selected))
                {
                    GrupyDoPuli grupyDoPuli = new GrupyDoPuli();
                    Grupa group = new Grupa();
                    grupyDoPuli.Grupa = group;
                    grupyDoPuli.PulaId = VM.GrupyDoPuli.PulaId;

                    selectedItems.Add(selected);
                    Grupa grupa = _db.Grupa.Where(m => m.Nazwa == selected).FirstOrDefault();
                    grupyDoPuli.Grupa.Id = grupa.Id;
                    _db.GrupyDoPuli.Add(grupyDoPuli);
                    
                }

            }

            _db.SaveChanges();
            

            return RedirectToAction("AddWords", new { pulaId });
        }

        [HttpGet]
        public IActionResult AddWords(int pulaId)
        {
            WordsForBankViewModel VM = new WordsForBankViewModel();
            var words = _db.Word.Include(m => m.LevelCategory).Include(m => m.AreaCategory);
            VM.pulaId = pulaId;
            VM.word = words;
            return View(VM);
        }
        [HttpGet]
        public IActionResult AcceptWord(int pulaId, int wordId)
        {
            var word = _db.Word.Where(m => m.Id == wordId).FirstOrDefault();
            return View(word);
        }
        [HttpPost]
        [ActionName("AcceptWord")]
        public IActionResult AcceptWordPost(int pulaId, int wordId)
        {
            WyrazyPula wyrazDoPuli = new WyrazyPula();
            wyrazDoPuli.PulaId = pulaId;
            Word wyraz = new Word();
            wyrazDoPuli.Wyraz = wyraz;
            wyrazDoPuli.Wyraz = _db.Word.Where(m => m.Id == wordId).FirstOrDefault();
            _db.WyrazyPula.Add(wyrazDoPuli);
            _db.SaveChanges();
            return RedirectToAction("AddWords", new { pulaId});
        }
    }
}

LearningEnglishApp/LearningEnglishApp/Views/Shared/_ButtonsForTablePartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model).Replace("%2F", "/")">
            <i class="fas fa-user-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model).Replace("%2F", "/")">
            <i class="fas fa-info-circle"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model).Replace("%2F", "/")">
            <i class="fas fa-minus-circle"></i>
        </a>
    </div>
</td>

LearningEnglishApp/LearningEnglishApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearningEnglishApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" fixed-top>

            <a class="navbar-brand" href="#">
                <img src="~/img/logo.png" width="30" height="30" />
                LearningEnglishApp
            </a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    @if (User.IsInRole("Nauczyciel"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Teacher" asp-controller="Student" asp-action="Index">Uczniowie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Teacher" asp-controller="Grupa" asp-action="Index">Grupy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Teacher" asp-controller="Pula" asp-action="Index">Pule</a>
                        </li>
                    }
                    @if (User.IsInRole("Uczeń"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Uczen" asp-controller="Test" asp-action="Index">Pule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Uczen" asp-controller="Progress" asp-action="Index">Moje testy</a>
                        </li>
                    }
                </ul>
            </div>
            <div>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>
    @if (User.IsInRole("Admin"))
    {
        <div id="wrapper">

            <!-- Sidebar -->
            <ul class="sidebar navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">
                        <i class="far fa-user"></i>
                        <span>Użytkownicy</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="far fa-folder-open"></i>
                        <span>Kategorie</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                        <a class="dropdown-item" asp-area="Admin" asp-controller="LevelCategory" asp-action="Index">Poziomów</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-area="Admin" asp-controller="AreaCategory" asp-action="Index">Słów</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Admin" asp-controller="Words" asp-action="Index">
                        <i class="fab fa-stripe-s"></i>
                        <span>Słowa</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Teacher" asp-controller="Pula" asp-action="Index">
                        <i class="fas fa-expand"></i>
                        <span>Pule</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Teacher" asp-controller="Grupa" asp-action="Index">
                        <i class="far fa-plus-square"></i>
                        <span>Oceny</span>
                    </a>
                </li>
            </ul>
            <div class="container">
                <partial name="_CookieConsentPartial" />
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    }
    else
    {
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>     
    }
    
    <br/>
    <br/>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - LearningEnglishApp
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="https://kit.fontawesome.com/573c98a277.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        <script src="https://kit.fontawesome.com/573c98a277.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>